//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/project/controller/CarInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CarInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CarInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CarInputActions"",
    ""maps"": [
        {
            ""name"": ""CarControls"",
            ""id"": ""97479e29-f5a1-4824-9f72-d2b2ab657196"",
            ""actions"": [
                {
                    ""name"": ""Movefoward"",
                    ""type"": ""Button"",
                    ""id"": ""83916b19-3097-4a85-aa1a-4622e691e9df"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""74196728-f1ea-4fb4-9643-9b89d29e3a69"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drift"",
                    ""type"": ""Button"",
                    ""id"": ""6130a42d-db6f-4d59-a92f-4084f0915686"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""controllerturn"",
                    ""type"": ""Value"",
                    ""id"": ""e13f77f5-171c-4b1f-a6d0-38c2ae9d25ed"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""movebackward"",
                    ""type"": ""Button"",
                    ""id"": ""e70a68fc-f41d-438b-8d7a-ddec74a64908"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""turnleft"",
                    ""type"": ""Button"",
                    ""id"": ""6ad1c380-31f6-4790-ab89-ea74853b1105"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""turnright"",
                    ""type"": ""Button"",
                    ""id"": ""deaa035b-1803-4874-89e5-ec5732973540"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""turbo"",
                    ""type"": ""Button"",
                    ""id"": ""b231487f-2526-4cff-836d-f55ee89ea2df"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""underglow"",
                    ""type"": ""Button"",
                    ""id"": ""d4102735-3864-4934-abef-108780d8abb9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""lights"",
                    ""type"": ""Button"",
                    ""id"": ""6f5aac5b-c411-4b24-be01-816933cfe631"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b75068b7-5010-4719-86aa-0af4de8229e1"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movefoward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""661f4474-df22-4e68-b299-af48e8c66e0d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movefoward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efc5654f-ab39-43f6-a3e3-dcb944f36d7d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dae04b30-cfa5-4e55-a797-19e4cb4f8da3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""013a987d-d138-47f2-aecb-44b0c311cbad"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cbfd8c9-e9b3-4219-8fa1-ec2f988d4bac"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85126c79-ff45-465d-98ac-29d10c68d10a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controllerturn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d705de12-3bd8-48fd-bb03-4cdd2ed4f505"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movebackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c33332b-35cb-49cc-8f29-88e488718094"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movebackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b113dd4-bbfa-4d20-a565-07720a24e67a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""turnleft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""055e93f2-ba3c-4ef4-93a0-bfdb78afe5f1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""turnright"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ce4522c-fbfa-4c09-835a-44e3e4edfa5d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""turbo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""feece66d-d2b1-4c9e-a246-980468f9df6a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""turbo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecc093f7-c778-4f68-82f5-efddd9743ed3"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""turbo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d37cfaf-6556-46d2-b071-0fb69a64525c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""underglow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8ce154e-940e-4ba8-b9bb-62363eee4ee2"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""underglow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""961a3dfe-d6a9-4d99-bfd2-155930744183"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""lights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""107441e6-a69f-4ee3-a126-2a4f96a9f5cb"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""lights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""CarControls"",
            ""bindingGroup"": ""CarControls"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // CarControls
        m_CarControls = asset.FindActionMap("CarControls", throwIfNotFound: true);
        m_CarControls_Movefoward = m_CarControls.FindAction("Movefoward", throwIfNotFound: true);
        m_CarControls_Brake = m_CarControls.FindAction("Brake", throwIfNotFound: true);
        m_CarControls_Drift = m_CarControls.FindAction("Drift", throwIfNotFound: true);
        m_CarControls_controllerturn = m_CarControls.FindAction("controllerturn", throwIfNotFound: true);
        m_CarControls_movebackward = m_CarControls.FindAction("movebackward", throwIfNotFound: true);
        m_CarControls_turnleft = m_CarControls.FindAction("turnleft", throwIfNotFound: true);
        m_CarControls_turnright = m_CarControls.FindAction("turnright", throwIfNotFound: true);
        m_CarControls_turbo = m_CarControls.FindAction("turbo", throwIfNotFound: true);
        m_CarControls_underglow = m_CarControls.FindAction("underglow", throwIfNotFound: true);
        m_CarControls_lights = m_CarControls.FindAction("lights", throwIfNotFound: true);
    }

    ~@CarInputActions()
    {
        UnityEngine.Debug.Assert(!m_CarControls.enabled, "This will cause a leak and performance issues, CarInputActions.CarControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CarControls
    private readonly InputActionMap m_CarControls;
    private List<ICarControlsActions> m_CarControlsActionsCallbackInterfaces = new List<ICarControlsActions>();
    private readonly InputAction m_CarControls_Movefoward;
    private readonly InputAction m_CarControls_Brake;
    private readonly InputAction m_CarControls_Drift;
    private readonly InputAction m_CarControls_controllerturn;
    private readonly InputAction m_CarControls_movebackward;
    private readonly InputAction m_CarControls_turnleft;
    private readonly InputAction m_CarControls_turnright;
    private readonly InputAction m_CarControls_turbo;
    private readonly InputAction m_CarControls_underglow;
    private readonly InputAction m_CarControls_lights;
    public struct CarControlsActions
    {
        private @CarInputActions m_Wrapper;
        public CarControlsActions(@CarInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movefoward => m_Wrapper.m_CarControls_Movefoward;
        public InputAction @Brake => m_Wrapper.m_CarControls_Brake;
        public InputAction @Drift => m_Wrapper.m_CarControls_Drift;
        public InputAction @controllerturn => m_Wrapper.m_CarControls_controllerturn;
        public InputAction @movebackward => m_Wrapper.m_CarControls_movebackward;
        public InputAction @turnleft => m_Wrapper.m_CarControls_turnleft;
        public InputAction @turnright => m_Wrapper.m_CarControls_turnright;
        public InputAction @turbo => m_Wrapper.m_CarControls_turbo;
        public InputAction @underglow => m_Wrapper.m_CarControls_underglow;
        public InputAction @lights => m_Wrapper.m_CarControls_lights;
        public InputActionMap Get() { return m_Wrapper.m_CarControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CarControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICarControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CarControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarControlsActionsCallbackInterfaces.Add(instance);
            @Movefoward.started += instance.OnMovefoward;
            @Movefoward.performed += instance.OnMovefoward;
            @Movefoward.canceled += instance.OnMovefoward;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @Drift.started += instance.OnDrift;
            @Drift.performed += instance.OnDrift;
            @Drift.canceled += instance.OnDrift;
            @controllerturn.started += instance.OnControllerturn;
            @controllerturn.performed += instance.OnControllerturn;
            @controllerturn.canceled += instance.OnControllerturn;
            @movebackward.started += instance.OnMovebackward;
            @movebackward.performed += instance.OnMovebackward;
            @movebackward.canceled += instance.OnMovebackward;
            @turnleft.started += instance.OnTurnleft;
            @turnleft.performed += instance.OnTurnleft;
            @turnleft.canceled += instance.OnTurnleft;
            @turnright.started += instance.OnTurnright;
            @turnright.performed += instance.OnTurnright;
            @turnright.canceled += instance.OnTurnright;
            @turbo.started += instance.OnTurbo;
            @turbo.performed += instance.OnTurbo;
            @turbo.canceled += instance.OnTurbo;
            @underglow.started += instance.OnUnderglow;
            @underglow.performed += instance.OnUnderglow;
            @underglow.canceled += instance.OnUnderglow;
            @lights.started += instance.OnLights;
            @lights.performed += instance.OnLights;
            @lights.canceled += instance.OnLights;
        }

        private void UnregisterCallbacks(ICarControlsActions instance)
        {
            @Movefoward.started -= instance.OnMovefoward;
            @Movefoward.performed -= instance.OnMovefoward;
            @Movefoward.canceled -= instance.OnMovefoward;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @Drift.started -= instance.OnDrift;
            @Drift.performed -= instance.OnDrift;
            @Drift.canceled -= instance.OnDrift;
            @controllerturn.started -= instance.OnControllerturn;
            @controllerturn.performed -= instance.OnControllerturn;
            @controllerturn.canceled -= instance.OnControllerturn;
            @movebackward.started -= instance.OnMovebackward;
            @movebackward.performed -= instance.OnMovebackward;
            @movebackward.canceled -= instance.OnMovebackward;
            @turnleft.started -= instance.OnTurnleft;
            @turnleft.performed -= instance.OnTurnleft;
            @turnleft.canceled -= instance.OnTurnleft;
            @turnright.started -= instance.OnTurnright;
            @turnright.performed -= instance.OnTurnright;
            @turnright.canceled -= instance.OnTurnright;
            @turbo.started -= instance.OnTurbo;
            @turbo.performed -= instance.OnTurbo;
            @turbo.canceled -= instance.OnTurbo;
            @underglow.started -= instance.OnUnderglow;
            @underglow.performed -= instance.OnUnderglow;
            @underglow.canceled -= instance.OnUnderglow;
            @lights.started -= instance.OnLights;
            @lights.performed -= instance.OnLights;
            @lights.canceled -= instance.OnLights;
        }

        public void RemoveCallbacks(ICarControlsActions instance)
        {
            if (m_Wrapper.m_CarControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICarControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CarControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CarControlsActions @CarControls => new CarControlsActions(this);
    private int m_CarControlsSchemeIndex = -1;
    public InputControlScheme CarControlsScheme
    {
        get
        {
            if (m_CarControlsSchemeIndex == -1) m_CarControlsSchemeIndex = asset.FindControlSchemeIndex("CarControls");
            return asset.controlSchemes[m_CarControlsSchemeIndex];
        }
    }
    public interface ICarControlsActions
    {
        void OnMovefoward(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnDrift(InputAction.CallbackContext context);
        void OnControllerturn(InputAction.CallbackContext context);
        void OnMovebackward(InputAction.CallbackContext context);
        void OnTurnleft(InputAction.CallbackContext context);
        void OnTurnright(InputAction.CallbackContext context);
        void OnTurbo(InputAction.CallbackContext context);
        void OnUnderglow(InputAction.CallbackContext context);
        void OnLights(InputAction.CallbackContext context);
    }
}
